package ml.satgrie.pl.ue.model;
// Generated 31 mars 2021 � 17:28:15 by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Calendrier generated by hbm2java
 */
@Entity
@Table(name = "calendrier", catalog = "lastuebdd")

public class Calendrier implements java.io.Serializable {

	private Integer calendrierId;
	private Projet projet;
	private Integer calendrierTypeId;
	private Date calendrierDate;
	private String calendrierCommmentaires;
	private Integer lastModifiedBy;
	private Date lastModifiedDate;

	public Calendrier() {
	}

	public Calendrier(Projet projet, Integer calendrierTypeId, Date calendrierDate, String calendrierCommmentaires,
			Integer lastModifiedBy, Date lastModifiedDate) {
		this.projet = projet;
		this.calendrierTypeId = calendrierTypeId;
		this.calendrierDate = calendrierDate;
		this.calendrierCommmentaires = calendrierCommmentaires;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id

	@Column(name = "CalendrierID", unique = true, nullable = false)
	public Integer getCalendrierId() {
		return this.calendrierId;
	}

	public void setCalendrierId(Integer calendrierId) {
		this.calendrierId = calendrierId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProjetID")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@Column(name = "CalendrierTypeID")
	public Integer getCalendrierTypeId() {
		return this.calendrierTypeId;
	}

	public void setCalendrierTypeId(Integer calendrierTypeId) {
		this.calendrierTypeId = calendrierTypeId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CalendrierDate", length = 19)
	public Date getCalendrierDate() {
		return this.calendrierDate;
	}

	public void setCalendrierDate(Date calendrierDate) {
		this.calendrierDate = calendrierDate;
	}

	@Column(name = "CalendrierCommmentaires", length = 250)
	public String getCalendrierCommmentaires() {
		return this.calendrierCommmentaires;
	}

	public void setCalendrierCommmentaires(String calendrierCommmentaires) {
		this.calendrierCommmentaires = calendrierCommmentaires;
	}

	@Column(name = "LastModifiedBy")
	public Integer getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Integer lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedDate", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
