package ml.satgrie.pl.ue.model;
// Generated 31 mars 2021 � 17:28:15 by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Contractant generated by hbm2java
 */
@Entity
@Table(name = "contractant", catalog = "lastuebdd")

public class Contractant implements java.io.Serializable {

	private Integer contractantId;
	private Contractanttype contractanttype;
	private Projet projet;
	private String contractantNom;
	private String contractantSigle;
	private Integer contractantStatutId;
	private Integer lastModifiedBy;
	private Date lastModifiedDate;

	public Contractant() {
	}

	public Contractant(Contractanttype contractanttype, Projet projet, String contractantNom, String contractantSigle,
			Integer contractantStatutId, Integer lastModifiedBy, Date lastModifiedDate) {
		this.contractanttype = contractanttype;
		this.projet = projet;
		this.contractantNom = contractantNom;
		this.contractantSigle = contractantSigle;
		this.contractantStatutId = contractantStatutId;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id

	@Column(name = "ContractantID", unique = true, nullable = false)
	public Integer getContractantId() {
		return this.contractantId;
	}

	public void setContractantId(Integer contractantId) {
		this.contractantId = contractantId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ContractantTypeID_relation37")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	public Contractanttype getContractanttype() {
		return this.contractanttype;
	}

	public void setContractanttype(Contractanttype contractanttype) {
		this.contractanttype = contractanttype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProjetID")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@Column(name = "ContractantNom", length = 450)
	public String getContractantNom() {
		return this.contractantNom;
	}

	public void setContractantNom(String contractantNom) {
		this.contractantNom = contractantNom;
	}

	@Column(name = "ContractantSigle", length = 100)
	public String getContractantSigle() {
		return this.contractantSigle;
	}

	public void setContractantSigle(String contractantSigle) {
		this.contractantSigle = contractantSigle;
	}

	@Column(name = "ContractantStatutID")
	public Integer getContractantStatutId() {
		return this.contractantStatutId;
	}

	public void setContractantStatutId(Integer contractantStatutId) {
		this.contractantStatutId = contractantStatutId;
	}

	@Column(name = "LastModifiedBy")
	public Integer getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Integer lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedDate", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
