package ml.satgrie.pl.ue.model;
// Generated 31 mars 2021 � 17:28:15 by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Etatavancement generated by hbm2java
 */
@Entity
@Table(name = "etatavancement", catalog = "lastuebdd")

public class Etatavancement implements java.io.Serializable {

	private Integer etatAvancementId;
	private Projet projet;
	private String etatAvancementText;
	private Integer etatAvancementProjetId;
	private Date lastModifiedBy;
	private Date lastModifiedDate;

	public Etatavancement() {
	}

	public Etatavancement(Projet projet) {
		this.projet = projet;
	}

	public Etatavancement(Projet projet, String etatAvancementText, Integer etatAvancementProjetId, Date lastModifiedBy,
			Date lastModifiedDate) {
		this.projet = projet;
		this.etatAvancementText = etatAvancementText;
		this.etatAvancementProjetId = etatAvancementProjetId;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id
	@Column(name = "EtatAvancementID", unique = true, nullable = false)
	public Integer getEtatAvancementId() {
		return this.etatAvancementId;
	}

	public void setEtatAvancementId(Integer etatAvancementId) {
		this.etatAvancementId = etatAvancementId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProjetID", nullable = false)
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@Column(name = "EtatAvancementText", length = 45)
	public String getEtatAvancementText() {
		return this.etatAvancementText;
	}

	public void setEtatAvancementText(String etatAvancementText) {
		this.etatAvancementText = etatAvancementText;
	}

	@Column(name = "EtatAvancementProjetID")
	public Integer getEtatAvancementProjetId() {
		return this.etatAvancementProjetId;
	}

	public void setEtatAvancementProjetId(Integer etatAvancementProjetId) {
		this.etatAvancementProjetId = etatAvancementProjetId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedBy", length = 19)
	public Date getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Date lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedDate", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
