package ml.satgrie.pl.ue.model;
// Generated 31 mars 2021 � 17:28:15 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Instrumentfinancement generated by hbm2java
 */
@Entity
@Table(name = "instrumentfinancement", catalog = "lastuebdd")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Cacheable
public class Instrumentfinancement implements java.io.Serializable {

	private Integer instrumentfinancementId;
	private SourceFinancement sourcefinancement;
	private String instrumentFinancementNom;
	private Integer lastModifiedBy;
	private Date lastModifiedDate;
	private String instrumentFinancementDesc;
	private Set<Budget> budgets = new HashSet<Budget>(0);

	public Instrumentfinancement() {
	}

	public Instrumentfinancement(SourceFinancement sourcefinancement, String instrumentFinancementNom,
			Integer lastModifiedBy, Date lastModifiedDate, String instrumentFinancementDesc, Set<Budget> budgets) {
		this.sourcefinancement = sourcefinancement;
		this.instrumentFinancementNom = instrumentFinancementNom;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.instrumentFinancementDesc = instrumentFinancementDesc;
		this.budgets = budgets;
	}

	@Id

	@Column(name = "instrumentfinancementID", unique = true, nullable = false)
	public Integer getInstrumentfinancementId() {
		return this.instrumentfinancementId;
	}

	public void setInstrumentfinancementId(Integer instrumentfinancementId) {
		this.instrumentfinancementId = instrumentfinancementId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SourceFinancementID")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	public SourceFinancement getSourcefinancement() {
		return this.sourcefinancement;
	}

	public void setSourcefinancement(SourceFinancement sourcefinancement) {
		this.sourcefinancement = sourcefinancement;
	}

	@Column(name = "InstrumentFinancementNom", length = 250)
	public String getInstrumentFinancementNom() {
		return this.instrumentFinancementNom;
	}

	public void setInstrumentFinancementNom(String instrumentFinancementNom) {
		this.instrumentFinancementNom = instrumentFinancementNom;
	}

	@Column(name = "LastModifiedBy")
	public Integer getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Integer lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedDate", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "InstrumentFinancementDesc", length = 250)
	public String getInstrumentFinancementDesc() {
		return this.instrumentFinancementDesc;
	}

	public void setInstrumentFinancementDesc(String instrumentFinancementDesc) {
		this.instrumentFinancementDesc = instrumentFinancementDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instrumentfinancement")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	public Set<Budget> getBudgets() {
		return this.budgets;
	}

	public void setBudgets(Set<Budget> budgets) {
		this.budgets = budgets;
	}

}
