package ml.satgrie.pl.ue.model;
// Generated 31 mars 2021 � 17:28:15 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.List;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Localisation generated by hbm2java
 */
@Entity
@Table(name = "localisation", catalog = "lastuebdd")

public class Localisation implements java.io.Serializable {

	private LocalisationId id;
	private String localisationLat;
	private String localisationLong;
	private Integer localisationLastModifiedBy;
	private String localisationCustomLat;
	private String localisationCustomLong;
	private String localisationDescActifs;
	private Date localisationLastModifiedDate;
	private Integer projetId;

	public Localisation() {
	}

	public Localisation(LocalisationId id) {
		this.id = id;
	}

	public Localisation(LocalisationId id, String localisationLat, String localisationLong,
			Integer localisationLastModifiedBy, String localisationCustomLat, String localisationCustomLong,
			String localisationDescActifs, Date localisationLastModifiedDate, Integer projetId) {
		this.id = id;
		this.localisationLat = localisationLat;
		this.localisationLong = localisationLong;
		this.localisationLastModifiedBy = localisationLastModifiedBy;
		this.localisationCustomLat = localisationCustomLat;
		this.localisationCustomLong = localisationCustomLong;
		this.localisationDescActifs = localisationDescActifs;
		this.localisationLastModifiedDate = localisationLastModifiedDate;
		this.projetId = projetId;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "paysId", column = @Column(name = "PaysID", nullable = false)),
			@AttributeOverride(name = "localisationId", column = @Column(name = "LocalisationID", nullable = false)),
			@AttributeOverride(name = "regionId", column = @Column(name = "RegionID", nullable = false)),
			@AttributeOverride(name = "cerlceId", column = @Column(name = "CerlceID", nullable = false)),
			@AttributeOverride(name = "communeId", column = @Column(name = "CommuneID", nullable = false)) })
	public LocalisationId getId() {
		return this.id;
	}

	public void setId(LocalisationId id) {
		this.id = id;
	}

	@Column(name = "LocalisationLat", length = 80)
	public String getLocalisationLat() {
		return this.localisationLat;
	}

	public void setLocalisationLat(String localisationLat) {
		this.localisationLat = localisationLat;
	}

	@Column(name = "LocalisationLong", length = 80)
	public String getLocalisationLong() {
		return this.localisationLong;
	}

	public void setLocalisationLong(String localisationLong) {
		this.localisationLong = localisationLong;
	}

	@Column(name = "LocalisationLastModifiedBy")
	public Integer getLocalisationLastModifiedBy() {
		return this.localisationLastModifiedBy;
	}

	public void setLocalisationLastModifiedBy(Integer localisationLastModifiedBy) {
		this.localisationLastModifiedBy = localisationLastModifiedBy;
	}

	@Column(name = "LocalisationCustomLat", length = 80)
	public String getLocalisationCustomLat() {
		return this.localisationCustomLat;
	}

	public void setLocalisationCustomLat(String localisationCustomLat) {
		this.localisationCustomLat = localisationCustomLat;
	}

	@Column(name = "LocalisationCustomLong", length = 80)
	public String getLocalisationCustomLong() {
		return this.localisationCustomLong;
	}

	public void setLocalisationCustomLong(String localisationCustomLong) {
		this.localisationCustomLong = localisationCustomLong;
	}

	@Column(name = "LocalisationDescActifs")
	public String getLocalisationDescActifs() {
		return this.localisationDescActifs;
	}

	public void setLocalisationDescActifs(String localisationDescActifs) {
		this.localisationDescActifs = localisationDescActifs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LocalisationLastModifiedDate", length = 19)
	public Date getLocalisationLastModifiedDate() {
		return this.localisationLastModifiedDate;
	}

	public void setLocalisationLastModifiedDate(Date localisationLastModifiedDate) {
		this.localisationLastModifiedDate = localisationLastModifiedDate;
	}

	@Column(name = "ProjetID")
	public Integer getProjetId() {
		return this.projetId;
	}

	public void setProjetId(Integer projetId) {
		this.projetId = projetId;
	}
}
