package ml.satgrie.pl.ue.model;
// Generated 31 mars 2021 � 17:28:15 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Pays generated by hbm2java
 */
@Entity
@Table(name = "pays", catalog = "lastuebdd")

public class Pays implements java.io.Serializable {

	private Integer paysId;
	private String paysNom;
	private String paysflag;
	private Integer paysLastModifiedBy;
	private Date lastMidifiedDate;
	private String abbrev2;
	private String abbrev3;
	private Set<Region> regions = new HashSet<Region>(0);

	public Pays() {
	}

	public Pays(String paysNom, String paysflag, Integer paysLastModifiedBy, Date lastMidifiedDate, String abbrev2,
			String abbrev3, Set<Region> regions) {
		this.paysNom = paysNom;
		this.paysflag = paysflag;
		this.paysLastModifiedBy = paysLastModifiedBy;
		this.lastMidifiedDate = lastMidifiedDate;
		this.abbrev2 = abbrev2;
		this.abbrev3 = abbrev3;
		this.regions = regions;
	}

	@Id

	@Column(name = "PaysID", unique = true, nullable = false)
	public Integer getPaysId() {
		return this.paysId;
	}

	public void setPaysId(Integer paysId) {
		this.paysId = paysId;
	}

	@Column(name = "PaysNom", length = 100)
	public String getPaysNom() {
		return this.paysNom;
	}

	public void setPaysNom(String paysNom) {
		this.paysNom = paysNom;
	}

	@Column(name = "paysflag", length = 45)
	public String getPaysflag() {
		return this.paysflag;
	}

	public void setPaysflag(String paysflag) {
		this.paysflag = paysflag;
	}

	@Column(name = "PaysLastModifiedBy")
	public Integer getPaysLastModifiedBy() {
		return this.paysLastModifiedBy;
	}

	public void setPaysLastModifiedBy(Integer paysLastModifiedBy) {
		this.paysLastModifiedBy = paysLastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastMidifiedDate", length = 19)
	public Date getLastMidifiedDate() {
		return this.lastMidifiedDate;
	}

	public void setLastMidifiedDate(Date lastMidifiedDate) {
		this.lastMidifiedDate = lastMidifiedDate;
	}

	@Column(name = "Abbrev2", length = 45)
	public String getAbbrev2() {
		return this.abbrev2;
	}

	public void setAbbrev2(String abbrev2) {
		this.abbrev2 = abbrev2;
	}

	@Column(name = "Abbrev3", length = 45)
	public String getAbbrev3() {
		return this.abbrev3;
	}

	public void setAbbrev3(String abbrev3) {
		this.abbrev3 = abbrev3;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pays")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	public Set<Region> getRegions() {
		return this.regions;
	}

	public void setRegions(Set<Region> regions) {
		this.regions = regions;
	}

}
