package ml.satgrie.pl.ue.model;
// Generated 31 mars 2021 � 17:28:15 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Photo generated by hbm2java
 */
@Entity
@Table(name = "photo", catalog = "lastuebdd")

public class Photo implements java.io.Serializable {

	private Integer photoId;
	private Projet projet;
	private String photoUrl;
	private String photoNom;
	private Integer photoType;
	private Integer localisationId;
	private BigDecimal photoLat;
	private BigDecimal photoLong;
	private Integer lastModifiedBy;
	private Date lastModifiedDate;

	public Photo() {
	}

	public Photo(Projet projet, String photoUrl, String photoNom, Integer photoType, Integer localisationId,
			BigDecimal photoLat, BigDecimal photoLong, Integer lastModifiedBy, Date lastModifiedDate) {
		this.projet = projet;
		this.photoUrl = photoUrl;
		this.photoNom = photoNom;
		this.photoType = photoType;
		this.localisationId = localisationId;
		this.photoLat = photoLat;
		this.photoLong = photoLong;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id

	@Column(name = "PhotoID", unique = true, nullable = false)
	public Integer getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(Integer photoId) {
		this.photoId = photoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProjetID")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@Column(name = "PhotoURL", length = 250)
	public String getPhotoUrl() {
		return this.photoUrl;
	}

	public void setPhotoUrl(String photoUrl) {
		this.photoUrl = photoUrl;
	}

	@Column(name = "PhotoNom", length = 250)
	public String getPhotoNom() {
		return this.photoNom;
	}

	public void setPhotoNom(String photoNom) {
		this.photoNom = photoNom;
	}

	@Column(name = "PhotoType")
	public Integer getPhotoType() {
		return this.photoType;
	}

	public void setPhotoType(Integer photoType) {
		this.photoType = photoType;
	}

	@Column(name = "LocalisationID")
	public Integer getLocalisationId() {
		return this.localisationId;
	}

	public void setLocalisationId(Integer localisationId) {
		this.localisationId = localisationId;
	}

	@Column(name = "PhotoLat", scale = 0)
	public BigDecimal getPhotoLat() {
		return this.photoLat;
	}

	public void setPhotoLat(BigDecimal photoLat) {
		this.photoLat = photoLat;
	}

	@Column(name = "PhotoLong", scale = 0)
	public BigDecimal getPhotoLong() {
		return this.photoLong;
	}

	public void setPhotoLong(BigDecimal photoLong) {
		this.photoLong = photoLong;
	}

	@Column(name = "LastModifiedBy")
	public Integer getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Integer lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedDate", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
