package ml.satgrie.pl.ue.model;
// Generated 31 mars 2021 � 17:28:15 by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Pointfocal generated by hbm2java
 */
@Entity
@Table(name = "pointfocal", catalog = "lastuebdd")

public class Pointfocal implements java.io.Serializable {

	private Integer pointFocalId;
	private Projet projet;
	private String pointFocalNom;
	private String pointFocalPrenoms;
	private String pointFocalTitre;
	private String pointFocalTelephone;
	private String pointFocalEmail;
	private String pointFocalSiteWeb;
	private Integer pointFocalTypeId;
	private Integer pointFocalEntityIdfk;
	private Integer lastModifiedBy;
	private Date lastModifiedDate;

	public Pointfocal() {
	}

	public Pointfocal(Projet projet, String pointFocalNom, String pointFocalPrenoms, String pointFocalTitre,
			String pointFocalTelephone, String pointFocalEmail, String pointFocalSiteWeb, Integer pointFocalTypeId,
			Integer pointFocalEntityIdfk, Integer lastModifiedBy, Date lastModifiedDate) {
		this.projet = projet;
		this.pointFocalNom = pointFocalNom;
		this.pointFocalPrenoms = pointFocalPrenoms;
		this.pointFocalTitre = pointFocalTitre;
		this.pointFocalTelephone = pointFocalTelephone;
		this.pointFocalEmail = pointFocalEmail;
		this.pointFocalSiteWeb = pointFocalSiteWeb;
		this.pointFocalTypeId = pointFocalTypeId;
		this.pointFocalEntityIdfk = pointFocalEntityIdfk;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id

	@Column(name = "PointFocalID", unique = true, nullable = false)
	public Integer getPointFocalId() {
		return this.pointFocalId;
	}

	public void setPointFocalId(Integer pointFocalId) {
		this.pointFocalId = pointFocalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProjetID")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@Column(name = "PointFocalNom", length = 250)
	public String getPointFocalNom() {
		return this.pointFocalNom;
	}

	public void setPointFocalNom(String pointFocalNom) {
		this.pointFocalNom = pointFocalNom;
	}

	@Column(name = "PointFocalPrenoms", length = 250)
	public String getPointFocalPrenoms() {
		return this.pointFocalPrenoms;
	}

	public void setPointFocalPrenoms(String pointFocalPrenoms) {
		this.pointFocalPrenoms = pointFocalPrenoms;
	}

	@Column(name = "PointFocalTitre", length = 250)
	public String getPointFocalTitre() {
		return this.pointFocalTitre;
	}

	public void setPointFocalTitre(String pointFocalTitre) {
		this.pointFocalTitre = pointFocalTitre;
	}

	@Column(name = "PointFocalTelephone", length = 250)
	public String getPointFocalTelephone() {
		return this.pointFocalTelephone;
	}

	public void setPointFocalTelephone(String pointFocalTelephone) {
		this.pointFocalTelephone = pointFocalTelephone;
	}

	@Column(name = "PointFocalEmail", length = 250)
	public String getPointFocalEmail() {
		return this.pointFocalEmail;
	}

	public void setPointFocalEmail(String pointFocalEmail) {
		this.pointFocalEmail = pointFocalEmail;
	}

	@Column(name = "PointFocalSiteWeb", length = 250)
	public String getPointFocalSiteWeb() {
		return this.pointFocalSiteWeb;
	}

	public void setPointFocalSiteWeb(String pointFocalSiteWeb) {
		this.pointFocalSiteWeb = pointFocalSiteWeb;
	}

	@Column(name = "PointFocalTypeID")
	public Integer getPointFocalTypeId() {
		return this.pointFocalTypeId;
	}

	public void setPointFocalTypeId(Integer pointFocalTypeId) {
		this.pointFocalTypeId = pointFocalTypeId;
	}

	@Column(name = "PointFocalEntityIDFK")
	public Integer getPointFocalEntityIdfk() {
		return this.pointFocalEntityIdfk;
	}

	public void setPointFocalEntityIdfk(Integer pointFocalEntityIdfk) {
		this.pointFocalEntityIdfk = pointFocalEntityIdfk;
	}

	@Column(name = "LastModifiedBy")
	public Integer getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Integer lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedDate", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
