package ml.satgrie.pl.ue.model;
// Generated 31 mars 2021 � 17:28:15 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Cacheable;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Projetchapitre generated by hbm2java
 */
@Entity
@Table(name = "projetchapitre", catalog = "lastuebdd")

public class Projetchapitre implements java.io.Serializable {

	private Integer id;
	private int projetId;
	private int formerSectorId;
	private String type;

	public Projetchapitre() {
	}

	public Projetchapitre(int projetId, int formerSectorId, String type) {
		this.projetId = projetId;
		this.formerSectorId = formerSectorId;
		this.type = type;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ProjetID", nullable = false)
	public int getProjetId() {
		return this.projetId;
	}

	public void setProjetId(int projetId) {
		this.projetId = projetId;
	}

	@Column(name = "formerSectorID", nullable = false)
	public int getFormerSectorId() {
		return this.formerSectorId;
	}

	public void setFormerSectorId(int formerSectorId) {
		this.formerSectorId = formerSectorId;
	}

	@Column(name = "Type", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
