package ml.satgrie.pl.ue.model;
// Generated 31 mars 2021 � 17:28:15 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * RegionId generated by hbm2java
 */
@Embeddable
public class RegionId implements java.io.Serializable {

	private int paysId;
	private int regionId;

	public RegionId() {
	}

	public RegionId(int paysId, int regionId) {
		this.paysId = paysId;
		this.regionId = regionId;
	}

	@Column(name = "PaysID", nullable = false)
	public int getPaysId() {
		return this.paysId;
	}

	public void setPaysId(int paysId) {
		this.paysId = paysId;
	}
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "RegionID", nullable = false)
	public int getRegionId() {
		return this.regionId;
	}

	public void setRegionId(int regionId) {
		this.regionId = regionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegionId))
			return false;
		RegionId castOther = (RegionId) other;

		return (this.getPaysId() == castOther.getPaysId()) && (this.getRegionId() == castOther.getRegionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPaysId();
		result = 37 * result + this.getRegionId();
		return result;
	}

}
