package ml.satgrie.pl.ue.model;
// Generated 31 mars 2021 � 17:28:15 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * SecteurId generated by hbm2java
 */
@Embeddable
public class SecteurId implements java.io.Serializable {

	private int chapitreId;
	private int secteurId;

	public SecteurId() {
	}

	public SecteurId(int chapitreId, int secteurId) {
		this.chapitreId = chapitreId;
		this.secteurId = secteurId;
	}

	@Column(name = "ChapitreID", nullable = false)
	public int getChapitreId() {
		return this.chapitreId;
	}

	public void setChapitreId(int chapitreId) {
		this.chapitreId = chapitreId;
	}
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "SecteurID", nullable = false)
	public int getSecteurId() {
		return this.secteurId;
	}

	public void setSecteurId(int secteurId) {
		this.secteurId = secteurId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SecteurId))
			return false;
		SecteurId castOther = (SecteurId) other;

		return (this.getChapitreId() == castOther.getChapitreId()) && (this.getSecteurId() == castOther.getSecteurId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getChapitreId();
		result = 37 * result + this.getSecteurId();
		return result;
	}

}
