package ml.satgrie.pl.ue.model;
// Generated 30 mars 2021 � 17:13:07 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Sourcefinancement generated by hbm2java
 */
@Entity
@Table(name = "sourcefinancement", catalog = "lastuebdd")

public class SourceFinancement implements java.io.Serializable {

	private Integer sourceFinancementId;
	private String sourceFinancementNom;
	private Integer sourceFinancementProjetId;
	private Integer lastModifiedBy;
	private Date lastModifiedDate;
	private String sourceFinancementDesc;
	private List<Instrumentfinancement> instrumentfinancements = new ArrayList<Instrumentfinancement>();
	private List<Utilisateur> utilisateurs;

	public SourceFinancement() {
	}

	public SourceFinancement(String sourceFinancementNom, Integer sourceFinancementProjetId, Integer lastModifiedBy,
			Date lastModifiedDate, String sourceFinancementDesc, List<Instrumentfinancement> instrumentfinancements, List<Utilisateur> utilisateurs) {
		this.sourceFinancementNom = sourceFinancementNom;
		this.sourceFinancementProjetId = sourceFinancementProjetId;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.sourceFinancementDesc = sourceFinancementDesc;
		this.instrumentfinancements = instrumentfinancements;
		this.utilisateurs = utilisateurs;
	}

	@Id

	@Column(name = "SourceFinancementID", unique = true, nullable = false)
	public Integer getSourceFinancementId() {
		return this.sourceFinancementId;
	}

	public void setSourceFinancementId(Integer sourceFinancementId) {
		this.sourceFinancementId = sourceFinancementId;
	}

	@Column(name = "SourceFinancementNom", length = 250)
	public String getSourceFinancementNom() {
		return this.sourceFinancementNom;
	}

	public void setSourceFinancementNom(String sourceFinancementNom) {
		this.sourceFinancementNom = sourceFinancementNom;
	}

	@Column(name = "SourceFinancementProjetID")
	public Integer getSourceFinancementProjetId() {
		return this.sourceFinancementProjetId;
	}

	public void setSourceFinancementProjetId(Integer sourceFinancementProjetId) {
		this.sourceFinancementProjetId = sourceFinancementProjetId;
	}

	@Column(name = "LastModifiedBy")
	public Integer getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Integer lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModifiedDate", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "SourceFinancementDesc", length = 250)
	public String getSourceFinancementDesc() {
		return this.sourceFinancementDesc;
	}

	public void setSourceFinancementDesc(String sourceFinancementDesc) {
		this.sourceFinancementDesc = sourceFinancementDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sourcefinancement")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	public List<Instrumentfinancement> getInstrumentfinancements() {
		return this.instrumentfinancements;
	}

	public void setInstrumentfinancements(List<Instrumentfinancement> instrumentfinancements) {
		this.instrumentfinancements = instrumentfinancements;
	}

	/**
	 * @return the utilisateurs
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sourcefinancement")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	public List<Utilisateur> getUtilisateurs() {
		return utilisateurs;
	}

	/**
	 * @param utilisateurs the utilisateurs to set
	 */
	public void setUtilisateurs(List<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
