package ml.satgrie.pl.ue.model;
// Generated 31 mars 2021 � 17:28:15 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SoussecteurId generated by hbm2java
 */
@Embeddable
public class SousSecteurId implements java.io.Serializable {

	private int chapitreId;
	private int secteurId;
	private int sousSecteurId;

	public SousSecteurId() {
		
	}

	public SousSecteurId(int chapitreId, int secteurId, int sousSecteurId) {
		this.chapitreId = chapitreId;
		this.secteurId = secteurId;
		this.sousSecteurId = sousSecteurId;
	}

	@Column(name = "ChapitreID", nullable = false)
	public int getChapitreId() {
		return this.chapitreId;
	}

	public void setChapitreId(int chapitreId) {
		this.chapitreId = chapitreId;
	}

	@Column(name = "SecteurID", nullable = false)
	public int getSecteurId() {
		return this.secteurId;
	}

	public void setSecteurId(int secteurId) {
		this.secteurId = secteurId;
	}

	@Column(name = "SousSecteurID", nullable = false)
	public int getSousSecteurId() {
		return this.sousSecteurId;
	}

	public void setSousSecteurId(int sousSecteurId) {
		this.sousSecteurId = sousSecteurId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SousSecteurId))
			return false;
		SousSecteurId castOther = (SousSecteurId) other;

		return (this.getChapitreId() == castOther.getChapitreId()) && (this.getSecteurId() == castOther.getSecteurId())
				&& (this.getSousSecteurId() == castOther.getSousSecteurId());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getChapitreId();
		result = 37 * result + this.getSecteurId();
		result = 37 * result + this.getSousSecteurId();
		return result;
	}

}
